image: prachi13k/build-tools:latest
stages:
  - init
  - tests
  - deploy

init:
  stage: init
  script:
    - pip install -r requirements.txt

run_tests:
  stage: tests
  script:
    - python tests.py

deploy_production:
  stage: deploy
  script:
    - python app.py